name: ZMK Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-pip python3-setuptools python3-wheel xz-utils file make gcc gcc-multilib

      - name: Install west
        run: pip3 install west

      - name: Init west
        run: |
          west init -m https://github.com/zmkfirmware/zmk.git zmk-workspace
          cd zmk-workspace
          west update

      - name: Copy config
        run: |
          cp -r config zmk-workspace/config

      - name: Build
        run: |
          cd zmk-workspace
          west build -s zmk/app -b nice_nano_v2 -- -DZMK_CONFIG=config

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: zmk-workspace/build/zephyr/zmk.uf2
