name: ZMK Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-pip python3-setuptools python3-wheel xz-utils file make gcc gcc-multilib

      - name: Install west
        run: pip3 install west

      - name: Init workspace
        run: |
          west init -m https://github.com/zmkfirmware/zmk.git --mr main zmk
          cd zmk
          west update

      - name: Copy config
        run: |
          cp -r ../config zmk/app/

      - name: Build
        run: |
          cd zmk
          west build -s app -b nice_nano_v2 -- -DZMK_CONFIG=app/config

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: zmk/build/zephyr/zmk.uf2
