name: Build ZMK Firmware

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - run: |
          sudo apt update
          sudo apt install -y git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-pip python3-setuptools python3-wheel xz-utils file make gcc gcc-multilib

      - run: pip3 install west

      - run: |
          west init -l config
          west update

      - run: |
          west build -b nice_nano_v2 app

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/zmk.uf2
